---
- name: Restart apt-daily.timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart apt-daily-upgrade.timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    enabled: true
    daemon_reload: true
